export const originalSections = [
  {
    code: 'CENTER',
    name: 'ศูนย์ครุภัณฑ์กลาง (Asset Center)',
    tel: '1000',
    building: 'อาคารสนับสนุนทางการแพทย์ ชั้น 1',
  },
  {
    code: 'MAINTENANCE',
    name: 'แผนกช่างและซ่อมบำรุง (Maintenance Department)',
    tel: '1020',
    building: 'อาคารสนับสนุนทางการแพทย์ ชั้น B1',
  },
  {
    code: 'IT',
    name: 'ศูนย์เทคโนโลยีสารสนเทศ (IT Department)',
    tel: '1234',
    building: 'อาคารบริหาร ชั้น 3',
  },
  {
    code: 'PARCEL',
    name: 'ฝ่ายพัสดุและจัดซื้อ (Parcel Department)',
    tel: '1050',
    building: 'อาคารบริหาร ชั้น 2',
  },
  {
    code: 'OPD',
    name: 'แผนกผู้ป่วยนอก (Outpatient Department)',
    tel: '1100',
    building: 'อาคารผู้ป่วยนอก ชั้น 1',
  },
  {
    code: 'ICU',
    name: 'แผนกผู้ป่วยวิกฤต (Intensive Care Unit)',
    tel: '1200',
    building: 'อาคารเฉลิมพระเกียรติ ชั้น 4',
  },
  {
    code: 'ER',
    name: 'แผนกอุบัติเหตุและฉุกเฉิน (Emergency Room)',
    tel: '1999',
    building: 'อาคารเฉลิมพระเกียรติ ชั้น 1',
  },
  {
    code: 'SURGERY',
    name: 'แผนกห้องผ่าตัด (Operating Room)',
    tel: '1300',
    building: 'อาคารเฉลิมพระเกียรติ ชั้น 3',
  },
  {
    code: 'LAB',
    name: 'แผนกห้องปฏิบัติการและชันสูตร (Laboratory)',
    tel: '1400',
    building: 'อาคารเฉลิมพระเกียรติ ชั้น 2',
  },
  {
    code: 'XRAY',
    name: 'แผนกรังสีวิทยา (Radiology Department)',
    tel: '1500',
    building: 'อาคารผู้ป่วยนอก ชั้น 2',
  },
  {
    code: 'PHARMACY',
    name: 'แผนกเภสัชกรรม (Pharmacy Department)',
    tel: '1600',
    building: 'อาคารผู้ป่วยนอก ชั้น 1',
  },
];

export const originalUsers = [
  {
    employeeId: 'GOV-670001',
    userName: 'admin',
    firstname: 'สมชาย',
    lastname: 'แอดมินระบบ',
    email: 'admin@hospital.go.th',
    password: 'Admin@1234',
    role: 'ADMIN' as const,
    sectionCode: 'IT',
  },
  {
    employeeId: 'GOV-670028',
    userName: 'admin_backup',
    firstname: 'อรทัย',
    lastname: 'ผู้ดูแลระบบสำรอง',
    email: 'admin.backup@hospital.go.th',
    password: 'AdminBackup@1234',
    role: 'ADMIN' as const,
    sectionCode: 'IT',
  },
  {
    employeeId: 'GOV-670002',
    userName: 'manager',
    firstname: 'ดร.วิชัย',
    lastname: 'ผู้อำนวยการฝ่ายบริหาร',
    email: 'manager@hospital.go.th',
    password: 'Manager@1234',
    role: 'MANAGER' as const,
    sectionCode: 'CENTER',
  },
  {
    employeeId: 'GOV-670003',
    userName: 'parcel',
    firstname: 'กรรณิการ์',
    lastname: 'พัสดุการเงิน',
    email: 'parcel@hospital.go.th',
    password: 'Parcel@1234',
    role: 'PARCEL_STAFF' as const,
    sectionCode: 'PARCEL',
  },
  {
    employeeId: 'GOV-670004',
    userName: 'assetcenter',
    firstname: 'ธนากร',
    lastname: 'เจ้าหน้าที่ศูนย์ครุภัณฑ์',
    email: 'assetcenter@hospital.go.th',
    password: 'AssetCenter@1234',
    role: 'ASSET_CENTER_STAFF' as const,
    sectionCode: 'CENTER',
  },
  {
    employeeId: 'GOV-670005',
    userName: 'deptstaff_opd1',
    firstname: 'วรรณภา',
    lastname: 'พยาบาลวิชาชีพ OPD 1',
    email: 'opd1@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'OPD',
  },
  {
    employeeId: 'GOV-670006',
    userName: 'deptstaff_opd2',
    firstname: 'อนุชา',
    lastname: 'พยาบาลวิชาชีพ OPD 2 (แผนกเดียวกันกับ OPD 1)',
    email: 'opd2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'OPD',
  },
  {
    employeeId: 'GOV-670007',
    userName: 'deptstaff_icu',
    firstname: 'ชลธิชา',
    lastname: 'พยาบาลวิชาชีพ ICU (ต่างแผนก)',
    email: 'icu@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'ICU',
  },
  {
    employeeId: 'GOV-670008',
    userName: 'deptstaff_er',
    firstname: 'ภานุวัฒน์',
    lastname: 'พยาบาลฉุกเฉิน ER (ต่างแผนก)',
    email: 'er@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'ER',
  },
  {
    employeeId: 'GOV-670009',
    userName: 'maintenance',
    firstname: 'ประเสริฐ',
    lastname: 'วิศวกรชีวการแพทย์',
    email: 'maintenance@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_STAFF' as const,
    sectionCode: 'MAINTENANCE',
  },
  // Additional users ensuring at least 2 users per section
  {
    employeeId: 'GOV-670010',
    userName: 'deptstaff_it2',
    firstname: 'พิชิต',
    lastname: 'เจ้าหน้าที่เทคโนโลยีสารสนเทศ 2',
    email: 'it2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'IT',
  },
  {
    employeeId: 'GOV-670011',
    userName: 'parcel2',
    firstname: 'สุภาพร',
    lastname: 'เจ้าหน้าที่พัสดุจัดซื้อ 2',
    email: 'parcel2@hospital.go.th',
    password: 'Parcel@1234',
    role: 'PARCEL_STAFF' as const,
    sectionCode: 'PARCEL',
  },
  {
    employeeId: 'GOV-670012',
    userName: 'deptstaff_icu2',
    firstname: 'นภา',
    lastname: 'พยาบาลวิชาชีพ ICU 2',
    email: 'icu2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'ICU',
  },
  {
    employeeId: 'GOV-670013',
    userName: 'deptstaff_er2',
    firstname: 'วีระ',
    lastname: 'พยาบาลฉุกเฉิน ER 2',
    email: 'er2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'ER',
  },
  {
    employeeId: 'GOV-670014',
    userName: 'deptstaff_surgery1',
    firstname: 'วิภา',
    lastname: 'พยาบาลวิชาชีพ ห้องผ่าตัด 1',
    email: 'surgery1@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'SURGERY',
  },
  {
    employeeId: 'GOV-670015',
    userName: 'deptstaff_surgery2',
    firstname: 'กิตติ',
    lastname: 'พยาบาลวิชาชีพ ห้องผ่าตัด 2',
    email: 'surgery2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'SURGERY',
  },
  {
    employeeId: 'GOV-670016',
    userName: 'deptstaff_lab1',
    firstname: 'สมพงษ์',
    lastname: 'นักเทคนิคการแพทย์ 1',
    email: 'lab1@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'LAB',
  },
  {
    employeeId: 'GOV-670017',
    userName: 'deptstaff_lab2',
    firstname: 'นิภา',
    lastname: 'นักเทคนิคการแพทย์ 2',
    email: 'lab2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'LAB',
  },
  {
    employeeId: 'GOV-670018',
    userName: 'deptstaff_xray1',
    firstname: 'รังสรรค์',
    lastname: 'นักรังสีการแพทย์ 1',
    email: 'xray1@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'XRAY',
  },
  {
    employeeId: 'GOV-670019',
    userName: 'deptstaff_xray2',
    firstname: 'มยุรี',
    lastname: 'นักรังสีการแพทย์ 2',
    email: 'xray2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'XRAY',
  },
  {
    employeeId: 'GOV-670020',
    userName: 'deptstaff_pharm1',
    firstname: 'ธนินท์',
    lastname: 'เภสัชกรวิชาชีพ 1',
    email: 'pharm1@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'PHARMACY',
  },
  {
    employeeId: 'GOV-670021',
    userName: 'deptstaff_pharm2',
    firstname: 'พิมพ์',
    lastname: 'เภสัชกรวิชาชีพ 2',
    email: 'pharm2@hospital.go.th',
    password: 'DeptStaff@1234',
    role: 'DEPARTMENT_STAFF' as const,
    sectionCode: 'PHARMACY',
  },
  // ── Maintenance Heads & Technicians for Testing ────────────────────────────
  {
    employeeId: 'GOV-670022',
    userName: 'head_maintenance',
    firstname: 'สมศักดิ์',
    lastname: 'หัวหน้าฝ่ายวิศวกรรมการแพทย์',
    email: 'head_maintenance@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_HEAD' as const,
    sectionCode: 'MAINTENANCE',
  },
  {
    employeeId: 'GOV-670023',
    userName: 'head_it',
    firstname: 'ธีรเดช',
    lastname: 'หัวหน้างานเทคโนโลยีสารสนเทศ',
    email: 'head_it@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_HEAD' as const,
    sectionCode: 'MAINTENANCE',
  },
  {
    employeeId: 'GOV-670024',
    userName: 'mech_bio1',
    firstname: 'อนุพงษ์',
    lastname: 'ช่างเครื่องมือแพทย์ 1',
    email: 'mech_bio1@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_STAFF' as const,
    sectionCode: 'MAINTENANCE',
  },
  {
    employeeId: 'GOV-670025',
    userName: 'mech_bio2',
    firstname: 'ชัชชัย',
    lastname: 'ช่างเครื่องมือแพทย์ 2',
    email: 'mech_bio2@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_STAFF' as const,
    sectionCode: 'MAINTENANCE',
  },
  {
    employeeId: 'GOV-670026',
    userName: 'mech_it',
    firstname: 'วรวิทย์',
    lastname: 'ช่างเทคนิคคอมพิวเตอร์',
    email: 'mech_it@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_STAFF' as const,
    sectionCode: 'MAINTENANCE',
  },
  {
    employeeId: 'GOV-670027',
    userName: 'mech_general',
    firstname: 'บุญส่ง',
    lastname: 'ช่างซ่อมบำรุงทั่วไป/อาคาร',
    email: 'mech_general@hospital.go.th',
    password: 'Maintenance@1234',
    role: 'MAINTENANCE_STAFF' as const,
    sectionCode: 'MAINTENANCE',
  },
];
