import type { BorrowHistoryAsset } from "../types/borrowHistoryTypes"

export const mockBorrowHistoryAssets: BorrowHistoryAsset[] = [
  {
    id: "1",
    borrowCode: "BR-432123",
    assetId: "1",
    assetCode: "BPM-2565-012",
    assetName: "เครื่องวัดความดันโลหิตแบบสอดแขน",
    borrowerName: "นายสมชาย สายเปย์",
    department: "แผนกการเงิน",
    borrowDate: "01 มี.ค. 2569",
    borrowTime: "09:15 น.",
    returnDate: "05 มี.ค. 2569",
    returnTime: "14:30 น.",
    status: "คืนแล้ว",
  },
  {
    id: "2",
    borrowCode: "BR-432122",
    assetId: "2",
    assetCode: "IVP-2566-045",
    assetName: "เครื่องให้สารละลายทางหลอดเลือด (IV Pump)",
    borrowerName: "นายซึเกะ ลาเสาร์",
    department: "แผนกห้องฉุกเฉิน",
    borrowDate: "10 มี.ค. 2569",
    borrowTime: "13:00 น.",
    returnDate: "-",
    returnTime: "-",
    status: "ยังไม่คืน",
  },
  {
    id: "3",
    borrowCode: "BR-432121",
    assetId: "3",
    assetCode: "BED-2563-088",
    assetName: "เตียงผู้ป่วยไฟฟ้า 3 ไกร์",
    borrowerName: "นางสมศรี มีสตางค์",
    department: "แผนกผู้ป่วยนอก",
    borrowDate: "12 มี.ค. 2569",
    borrowTime: "10:20 น.",
    returnDate: "15 มี.ค. 2569",
    returnTime: "17:00 น.",
    status: "คืนแล้ว",
  },
  {
    id: "4",
    borrowCode: "BR-432120",
    assetId: "4",
    assetCode: "WCH-2564-015",
    assetName: "รถเข็นผู้ป่วยนั่ง (Wheelchair)",
    borrowerName: "นาง มงคลกิตติ์ สุขสินธานนท์",
    department: "แผนกผู้ป่วยใน",
    borrowDate: "18 มี.ค. 2569",
    borrowTime: "15:45 น.",
    returnDate: "20 มี.ค. 2569",
    returnTime: "11:00 น.",
    status: "คืนแล้ว",
  },
]
