export const ROLES = {
  MAINTENANCE_STAFF: "MAINTENANCE_STAFF",
  DEPARTMENT_STAFF: "DEPARTMENT_STAFF",
  ASSET_CENTER_STAFF: "ASSET_CENTER_STAFF",
  PARCEL_STAFF: "PARCEL_STAFF",
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
} as const;

export type RoleType = (typeof ROLES)[keyof typeof ROLES];
