-- Align enum values used by the current application and demo seed with
-- databases built from the committed migration history.
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MAINTENANCE_HEAD';

ALTER TYPE "StepActionType" ADD VALUE IF NOT EXISTS 'WITH_PARTS';
ALTER TYPE "StepActionType" ADD VALUE IF NOT EXISTS 'UNREPAIRABLE';

-- Borrow extensions exist in the Prisma schema but were absent from the
-- historical migrations. Preserve installations that already created them.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type
    WHERE typname = 'BorrowExtensionType'
      AND typnamespace = 'public'::regnamespace
  ) THEN
    CREATE TYPE "BorrowExtensionType" AS ENUM ('DESK', 'ONLINE');
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_type
    WHERE typname = 'BorrowExtensionStatus'
      AND typnamespace = 'public'::regnamespace
  ) THEN
    CREATE TYPE "BorrowExtensionStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
  END IF;
END $$;

ALTER TYPE "BorrowExtensionType" ADD VALUE IF NOT EXISTS 'DESK';
ALTER TYPE "BorrowExtensionType" ADD VALUE IF NOT EXISTS 'ONLINE';
ALTER TYPE "BorrowExtensionStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "BorrowExtensionStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "BorrowExtensionStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "BorrowExtensionStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

-- Older borrowing rows need a unique number before the required column can
-- be enforced. New borrowing numbers are generated by the application.
ALTER TABLE "borrow_transaction"
  ADD COLUMN IF NOT EXISTS "borrow_no" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "expected_return_date" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "extension_count" INTEGER NOT NULL DEFAULT 0;

UPDATE "borrow_transaction"
SET "borrow_no" = 'LEGACY-' || md5("borrow_transaction_id")
WHERE "borrow_no" IS NULL;

ALTER TABLE "borrow_transaction"
  ALTER COLUMN "borrow_no" SET NOT NULL;

ALTER TABLE "company"
  ALTER COLUMN "tel" SET DATA TYPE VARCHAR(100),
  ALTER COLUMN "fax" SET DATA TYPE VARCHAR(255);

ALTER TABLE "repair_job"
  ADD COLUMN IF NOT EXISTS "repair_cost" DECIMAL(15,2),
  ADD COLUMN IF NOT EXISTS "unrepairable_reason" TEXT;

ALTER TABLE "sparepart_txns"
  ADD COLUMN IF NOT EXISTS "stock_type" VARCHAR(20);

CREATE TABLE IF NOT EXISTS "borrow_extension" (
  "borrow_extension_id" TEXT NOT NULL,
  "borrow_transaction_id" TEXT NOT NULL,
  "extension_type" "BorrowExtensionType" NOT NULL,
  "status" "BorrowExtensionStatus" NOT NULL DEFAULT 'PENDING',
  "round_number" INTEGER NOT NULL DEFAULT 1,
  "current_return_date" TIMESTAMP(3) NOT NULL,
  "requested_return_date" TIMESTAMP(3) NOT NULL,
  "reason" TEXT NOT NULL,
  "reject_reason" TEXT,
  "requested_by_user_id" TEXT NOT NULL,
  "reviewed_by_user_id" TEXT,
  "reviewed_at" TIMESTAMP(3),
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "borrow_extension_pkey" PRIMARY KEY ("borrow_extension_id")
);

CREATE INDEX IF NOT EXISTS "borrow_extension_borrow_transaction_id_idx"
  ON "borrow_extension"("borrow_transaction_id");
CREATE INDEX IF NOT EXISTS "borrow_extension_status_idx"
  ON "borrow_extension"("status");
CREATE INDEX IF NOT EXISTS "borrow_extension_requested_by_user_id_idx"
  ON "borrow_extension"("requested_by_user_id");
CREATE INDEX IF NOT EXISTS "borrow_extension_created_at_idx"
  ON "borrow_extension"("created_at");

CREATE INDEX IF NOT EXISTS "asset_section_id_idx" ON "asset"("section_id");
CREATE INDEX IF NOT EXISTS "asset_asset_status_id_idx" ON "asset"("asset_status_id");
CREATE INDEX IF NOT EXISTS "asset_availability_status_id_idx" ON "asset"("availability_status_id");
CREATE INDEX IF NOT EXISTS "asset_type_id_idx" ON "asset"("type_id");
CREATE INDEX IF NOT EXISTS "asset_created_at_idx" ON "asset"("created_at");
CREATE INDEX IF NOT EXISTS "asset_noid_idx" ON "asset"("noid");

CREATE UNIQUE INDEX IF NOT EXISTS "borrow_transaction_borrow_no_key"
  ON "borrow_transaction"("borrow_no");
CREATE INDEX IF NOT EXISTS "borrow_transaction_asset_id_idx" ON "borrow_transaction"("asset_id");
CREATE INDEX IF NOT EXISTS "borrow_transaction_borrower_id_idx" ON "borrow_transaction"("borrower_id");
CREATE INDEX IF NOT EXISTS "borrow_transaction_borrow_status_id_idx" ON "borrow_transaction"("borrow_status_id");
CREATE INDEX IF NOT EXISTS "borrow_transaction_expected_return_date_idx" ON "borrow_transaction"("expected_return_date");
CREATE INDEX IF NOT EXISTS "borrow_transaction_created_at_idx" ON "borrow_transaction"("created_at");

CREATE INDEX IF NOT EXISTS "mechanic_repair_job_id_idx" ON "mechanic_repair"("job_id");
CREATE INDEX IF NOT EXISTS "mechanic_repair_user_id_idx" ON "mechanic_repair"("user_id");

CREATE INDEX IF NOT EXISTS "repair_job_section_id_idx" ON "repair_job"("section_id");
CREATE INDEX IF NOT EXISTS "repair_job_job_status_id_idx" ON "repair_job"("job_status_id");
CREATE INDEX IF NOT EXISTS "repair_job_asset_id_idx" ON "repair_job"("asset_id");
CREATE INDEX IF NOT EXISTS "repair_job_reporter_id_idx" ON "repair_job"("reporter_id");
CREATE INDEX IF NOT EXISTS "repair_job_created_at_idx" ON "repair_job"("created_at");
CREATE INDEX IF NOT EXISTS "repair_job_due_date_idx" ON "repair_job"("due_date");
CREATE INDEX IF NOT EXISTS "repair_job_action_type_urgency_status_idx"
  ON "repair_job"("action_type", "urgency_status");

CREATE INDEX IF NOT EXISTS "repair_job_step_job_id_idx" ON "repair_job_step"("job_id");
CREATE INDEX IF NOT EXISTS "repair_job_step_step_master_id_idx" ON "repair_job_step"("step_master_id");
CREATE INDEX IF NOT EXISTS "sparepart_adds_sparepart_id_idx" ON "sparepart_adds"("sparepart_id");
CREATE INDEX IF NOT EXISTS "sparepart_txns_sparepart_id_idx" ON "sparepart_txns"("sparepart_id");
CREATE INDEX IF NOT EXISTS "sparepart_txns_job_id_idx" ON "sparepart_txns"("job_id");
CREATE INDEX IF NOT EXISTS "sparepart_txns_txn_type_idx" ON "sparepart_txns"("txn_type");
CREATE INDEX IF NOT EXISTS "spareparts_group_id_idx" ON "spareparts"("group_id");
CREATE INDEX IF NOT EXISTS "users_section_id_idx" ON "users"("section_id");
CREATE INDEX IF NOT EXISTS "users_role_idx" ON "users"("role");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'borrow_extension_borrow_transaction_id_fkey'
  ) THEN
    ALTER TABLE "borrow_extension"
      ADD CONSTRAINT "borrow_extension_borrow_transaction_id_fkey"
      FOREIGN KEY ("borrow_transaction_id")
      REFERENCES "borrow_transaction"("borrow_transaction_id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'borrow_extension_requested_by_user_id_fkey'
  ) THEN
    ALTER TABLE "borrow_extension"
      ADD CONSTRAINT "borrow_extension_requested_by_user_id_fkey"
      FOREIGN KEY ("requested_by_user_id")
      REFERENCES "users"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'borrow_extension_reviewed_by_user_id_fkey'
  ) THEN
    ALTER TABLE "borrow_extension"
      ADD CONSTRAINT "borrow_extension_reviewed_by_user_id_fkey"
      FOREIGN KEY ("reviewed_by_user_id")
      REFERENCES "users"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
